language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.5
  - 2.1
  - 2.2
  - 2.3
script: bundle exec rspec --color --format=documentation
addons:
  code_climate:
    repo_token: &codeclimate_token 6d4a51b47839a35d44ba7a899bd12e7cb4c519664cf2508724f8765210493ba2
env:
  global:
    - CODECLIMATE_REPO_TOKEN: *codeclimate_token
    - CI: true
branches:
  only:
    - master
    - /^staging.*$/
