language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
script: bundle exec rspec --color --format=documentation
addons:
  code_climate:
    repo_token: &codeclimate_token 6d4a51b47839a35d44ba7a899bd12e7cb4c519664cf2508724f8765210493ba2
env:
  global:
    - CODECLIMATE_REPO_TOKEN: *codeclimate_token
    - CI: true
branches:
  only:
    - master
    - /^staging.*$/
before_install:
  - gem update --system
